id: P003246
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN6819
  title: ལེ་ཧྥུང་གི་པར་རིས་མཛད་རྣམ།
  author: ''
  volumes:
    1fc68904876b449393596e970663faa4:
      image_group_id: I3CN6821
      title: ''
      volume_number: 1
      total_pages: 212
      base_file: v001.txt
